# Copy this file over mosquitto.conf after creating password.txt.
listener 1883
protocol mqtt
listener 9001
protocol websockets
allow_anonymous false
password_file /mosquitto/config/password.txt
acl_file /mosquitto/config/acl.txt
persistence true
persistence_location /mosquitto/data/
log_dest stdout
connection_messages true
log_timestamp true
max_queued_messages 1000
max_inflight_messages 20
message_size_limit 10240
